
module Common
  M_WIDTH=41
  M_HEIGHT=21
  M_HEIGHTSTEP=2
  M_WIDTHSTEP=4
  M_FIRSTX=2
  M_FIRSTY=1
  M_LASTX=38
  M_LASTY=19
  M_LOGICALX=10
  M_LOGICALY=10
  M_NUMOFSQUARES=M_LOGICALY*M_LOGICALX
  M_HORIZONTALLENGTH=(M_WIDTH-2)
  M_VERTICALLENGTH=(M_HEIGHT-2)
end
